// render-readme.mjs — renders README.md (EN) and README.zh.md from data/plugins.json.
// The registry is the single source of truth. After editing it, run: npm run render
import { readFile, writeFile } from 'node:fs/promises';

const registry = JSON.parse(await readFile(new URL('../data/plugins.json', import.meta.url), 'utf8'));
const suitsRegistry = JSON.parse(await readFile(new URL('../data/suits.json', import.meta.url), 'utf8'));

const CATEGORY_LABEL = {
  discovery: { en: 'Discovery & Management', zh: '发现与管理' },
  ui: { en: 'UI & Themes', zh: 'UI 与皮肤' },
  'terminal-desktop': { en: 'Terminal & Desktop', zh: '终端与桌面' },
  agents: { en: 'Agents & Workflow', zh: '多 Agent 与工作流' },
  usage: { en: 'Usage & Stats', zh: '用量与统计' },
  notifications: { en: 'Notifications & Alerts', zh: '通知与提醒' }
};
const CATEGORY_ORDER = ['discovery', 'ui', 'terminal-desktop', 'agents', 'usage', 'notifications'];
const TIER_LABEL = {
  featured: { en: '🏆 Featured · 编辑精选', zh: '🏆 编辑精选 · Featured' },
  listed: { en: '✅ Listed · 已收录', zh: '✅ 已收录 · Listed' },
  candidate: { en: '🧪 Candidates · 候选池', zh: '🧪 候选池 · Candidates' }
};

const featured = registry.plugins.filter(p => p.tier === 'featured');
const listed = registry.plugins.filter(p => p.tier === 'listed');
const candidates = registry.plugins.filter(p => p.tier === 'candidate');
const updated = registry.updatedAt;
const dshVersion = registry.dshVersion;

function badges() {
  return [
    '![license](https://img.shields.io/badge/license-MIT-green)',
    '![featured](https://img.shields.io/badge/featured-' + featured.length + '-ffb900)',
    '![listed](https://img.shields.io/badge/listed-' + listed.length + '-brightgreen)',
    '![candidates](https://img.shields.io/badge/candidates-' + candidates.length + '-9cf)',
    '![verified](https://img.shields.io/badge/verified-' + updated + '-blue)'
  ].join(' ');
}

function scoreLine(p, zh) {
  const s = p.score;
  const dims = zh ? ['体验', '维护', '安全', '兼容'] : ['experience', 'maintenance', 'security', 'compatibility'];
  const vals = [s.experience, s.maintenance, s.security, s.compatibility];
  const score = vals.map((v, i) => dims[i] + ' ' + v).join(' · ');
  return score + ' · ' + p.stars + '⭐ · ' + p.license + ' · ' + (zh ? '实测于 dsh ' : 'verified on dsh ') + p.verifiedAgainst + ' (' + p.lastVerified + ')';
}

function candidateLine(p, zh) {
  const parts = [p.stars + '⭐', p.license];
  parts.push(zh ? '机器体检 ' + p.security.scannedAt : 'machine pass ' + p.security.scannedAt);
  parts.push(p.manifestCompliant === true ? (zh ? '规范门槛 ✓' : 'spec gate ✓') : (zh ? '规范门槛 ✗（待补 whalepicks.json）' : 'spec gate ✗ (whalepicks.json pending)'));
  const flags = p.security.redFlags || [];
  if (flags.length) parts.push('⚠️ ' + flags.length + ' ' + (zh ? '项待复核' : 'flag(s) pending human review'));
  parts.push('[' + (zh ? '体检发现' : 'pass findings') + '](docs/security-report.md#' + p.id + ')');
  return parts.join(' · ');
}

function entryBlock(p, zh) {
  const desc = p.description[zh ? 'zh' : 'en'];
  let out = '- [' + p.name + '](https://github.com/' + p.repo + ') — ' + desc + '\n';
  out += '  <br><sub>' + (p.tier === 'candidate' ? candidateLine(p, zh) : scoreLine(p, zh)) + '</sub>\n';
  if (p.tier !== 'candidate' && p.reviewNotes) {
    out += '\n  > **' + (zh ? '创始人手记' : 'Founder’s notes') + '**: ' + p.reviewNotes[zh ? 'zh' : 'en'] + '\n';
  }
  if (p.tier !== 'candidate' && p.radar) {
    out += '\n  ![six-axis radar](assets/radar/' + p.id + '.svg "' + p.id + ' six-axis radar")\n';
  }
  if (p.install) {
    out += '\n  ```sh\n  ' + p.install + '\n  ```\n';
  }
  return out;
}

function catalog(zh) {
  const sections = [];
  for (const tier of ['featured', 'listed', 'candidate']) {
    const pools = { featured, listed, candidate: candidates };
    const pool = pools[tier];
    if (!pool.length) continue;
    const parts = ['## <a id="' + tier + '"></a>' + TIER_LABEL[tier][zh ? 'zh' : 'en'], ''];
    if (tier === 'candidate') {
      parts.push(zh
        ? '机器体检已完成，待创始人亲测后转正。试用体验、踩坑记录欢迎在 Issues 反馈——好的反馈会加速转正。'
        : 'Machine pass done; awaiting the founder’s hands-on test before promotion. Your trial notes and issues speed that up.');
      parts.push('');
    }
    for (const cat of CATEGORY_ORDER) {
      const items = pool.filter(p => p.category === cat);
      if (!items.length) continue;
      parts.push('### ' + CATEGORY_LABEL[cat][zh ? 'zh' : 'en'], '');
      for (const p of items) parts.push(entryBlock(p, zh));
    }
    sections.push(parts.join('\n'));
  }
  return sections.join('\n\n');
}

function body(zh) {
  const t = (en, cn) => (zh ? cn : en);
  return [
    '<!-- ⚠️ GENERATED by scripts/render-readme.mjs from data/plugins.json — do not edit by hand. Edit the registry, then run: npm run render -->',
    '',
    '# 🐳 dsh-whale-picks · 鲸选',
    '',
    t('**Install with confidence. Only the good stuff.** — the boutique store for DeepSeek Harness (`dsh`) plugins.',
      '**敢装，值得装。** —— DeepSeek Harness (`dsh`) 插件精品商店。'),
    '',
    t('[English](README.md) | [中文](README.zh.md)', '[中文](README.zh.md) | [English](README.md)'),
    '',
    badges(),
    '',
    t('> Big lists tell you **what exists**. The radar tells you **whether it runs**.\n> 鲸选 tells you **whether you should install it — and whether it is worth it**.',
      '> 大列表告诉你**有什么**。雷达告诉你**能不能跑**。\n> 鲸选告诉你**敢不敢装、值不值得装**。'),
    '',
    t(
      '[DeepSeek Harness](https://github.com/deepseek-ai/deepseek-harness) (`dsh`) is DeepSeek’s open-source agent harness where everything is a plugin. The ecosystem has thousands of candidate repos; this store carries only plugins the founder has personally installed and vetted. Every shelf item gets a machine security pass; every promoted item gets a four-dimension score, the founder’s notes, and a published decision. **宁缺毋滥 — few shelves, no filler.**',
      '[DeepSeek Harness](https://github.com/deepseek-ai/deepseek-harness) (`dsh`) 是 DeepSeek 的开源 agent harness，万物皆插件。生态里躺着几千个候选仓库；本店只收创始人**亲手装过、亲手验过**的插件。每件上架都经过机器安全体检；每件正式收录都有四维评分、创始人手记和公开的审核决定。**宁缺毋滥——货架少，但件件有出处。**'
    ),
    '',
    '## Tiers · 分级',
    '',
    t('- 🏆 **Featured · 编辑精选** — founder-tested, security pass, four-dimension score above the gate',
      '- 🏆 **编辑精选 · Featured** — 创始人亲测 + 安全体检 + 四维评分通过门槛'),
    t('- ✅ **Listed · 已收录** — same bar as Featured (candidates that passed)',
      '- ✅ **已收录 · Listed** — 与编辑精选同门槛（转正后的候选）'),
    t('- 🧪 **Candidates · 候选池** — machine security pass done, awaiting the founder’s hands-on test',
      '- 🧪 **候选池 · Candidates** — 机器体检已完成，待创始人亲测转正'),
    '',
    t('Every entry carries its exact install command. Most plugins install with `dsh plugin --profile <name> add <package>`; always read the linked repo’s README first.',
      '每个条目都带有确切的安装命令。多数插件用 `dsh plugin --profile <name> add <package>` 安装；安装前请先阅读对应仓库的 README。'),
    '',
    '## Contents',
    '',
    ...(featured.length ? [t('- [🏆 Featured](#featured)', '- [🏆 编辑精选](#featured)')] : []),
    ...(listed.length ? [t('- [✅ Listed](#listed)', '- [✅ 已收录](#listed)')] : []),
    ...(candidates.length ? [t('- [🧪 Candidates](#candidates)', '- [🧪 候选池](#candidates)')] : []),
    t('- [Security & method](docs/security-report.md)', '- [安全与体检方法](docs/security-report.md)'),
    t('- [Curation charter](docs/charter.md) · [Scoring rubric](docs/rubric.md) · [Decisions log](docs/decisions.md)',
      '- [选品宪章](docs/charter.md) · [评分标准](docs/rubric.md) · [决定流水](docs/decisions.md)'),
    t('- [Contributing](CONTRIBUTING.md) · [Roadmap](docs/roadmap.md)', '- [参与](CONTRIBUTING.md) · [路线图](docs/roadmap.md)'),
    '',
    catalog(zh),
    '',
    '## 🐳 Suits · 套件',
    '',
    ...(suitsRegistry.suits.length
      ? suitsRegistry.suits.map((s) => '- **' + s.name[zh ? 'zh' : 'en'] + '** — ' + s.description[zh ? 'zh' : 'en'] + '（' + s.plugins.join(' + ') + '）')
      : [zh
        ? '暂无套件——等已收录插件攒到可以组合的数量，套件会出现在这里（组合标准见 [docs/suits.md](docs/suits.md)）。宁缺毋滥，不造假。'
        : 'No suits yet — once enough plugins are listed to compose, suits appear here (criteria in [docs/suits.md](docs/suits.md)). 宁缺毋滥, no fake data.']),
    '',
    '## Security · 安全与体检',
    '',
    t(
      'Every entry — including candidates — gets a machine security pass before it appears here: license file, npm publication with an anti-squatting repository-pointer check, 6-month maintenance activity, and red-flag scanning. See the full method and its limits in the [security report](docs/security-report.md).',
      '每个条目（包括候选）在上架前都要过一遍机器安全体检：许可证文件、npm 发布与防冒名 repository 指针校验、近 6 个月维护活跃度、红旗扫描。完整方法学与局限见[体检报告](docs/security-report.md)。'
    ),
    '',
    t(
      '> ⚠️ **A security pass is not a security audit.** Installing a plugin runs third-party code on your machine with your own permissions — it can read your files, use your credentials and reach the network. Listing here is not an endorsement by DeepSeek; check the source before you install.',
      '> ⚠️ **体检不是审计。** 安装插件等于在你的机器上运行第三方代码——它能读你的文件、使用你的凭据、访问网络。收录不代表 DeepSeek 官方背书；安装前请自查源码。'
    ),
    '',
    '## Related · 大卖场',
    '',
    t('We deliberately do not compete on quantity. The wide lanes are covered by:', '本店刻意不做数量。大卖场们覆盖了广的部分：'),
    '',
    '- [awesome-dsh-plugin/awesome-dsh-plugin](https://github.com/awesome-dsh-plugin/awesome-dsh-plugin) — ' + t('what exists (big curated list)', '有什么（大而全的精选列表）'),
    '- [AdamPlatin123/awesome-dsh-plugins](https://github.com/AdamPlatin123/awesome-dsh-plugins) — ' + t('whether it runs (radar + k8s runtime tests)', '能不能跑（雷达 + k8s 实测）'),
    '- [dshworks/awesome-dsh-plugins](https://github.com/dshworks/awesome-dsh-plugins) — ' + t('machine-readable registry (1028 entries)', '机器可读数据（1028 条）'),
    '- [dsh-market/dsh-market](https://github.com/dsh-market/dsh-market) — ' + t('the in-DSH install market', 'DSH 内置安装市场'),
    '',
    t('Maintained against dsh **' + dshVersion + '** · registry updated ' + updated + '. [Roadmap](docs/roadmap.md): storefront website, the in-DSH 鲸选 boutique plugin, ratings & discussions.',
      '按 dsh **' + dshVersion + '** 维护 · registry 更新于 ' + updated + '。[路线图](docs/roadmap.md)：商店网站、DSH 内置鲸选插件、评分与讨论区。'),
    '',
    '## License',
    '',
    t('MIT © 2026 Leslie (LeeKai233) — code and registry data.', 'MIT © 2026 Leslie (LeeKai233) —— 代码与 registry 数据。')
  ].join('\n');
}

await writeFile(new URL('../README.md', import.meta.url), body(false) + '\n');
await writeFile(new URL('../README.zh.md', import.meta.url), body(true) + '\n');
console.log('rendered README.md + README.zh.md');
